name: Build and Publish to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches: [ develop branch ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.RELEASE_TOKEN}}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Prepare and Perform Maven Release
      run: mvn --batch-mode release:clean release:prepare release:perform -Darguments="-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true" -Dusername=${{ github.actor }} -Dpassword=${{ secrets.RELEASE_TOKEN }}

    - name: Publish to GitHub Packages
      run: mvn deploy

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: docker tag my-app ghcr.io/${{ github.repository }}/my-app:latest && docker push ghcr.io/${{ github.repository }}/my-app:latest
