name: Build, Publish, and Release on merge to main

on:
  pull_request:
    types: [closed]
<<<<<<< HEAD
    
    branches: [ main ]
=======
    branches: [main]
>>>>>>> 192a0139609ad1400db32d2c2f4c765fff674385

jobs:
  build_publish_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        token: ${{ secrets.RELEASE_TOKEN }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
      
    - name: Set Git identity
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        repositories: >-
          [
            {
              "id": "github",
              "url": "https://maven.pkg.github.com/bertrandmbanwi/java-hello-world-with-maven"
            }
          ]
        servers: >-
          [
            {
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.RELEASE_TOKEN }}"
            }
          ]

    - run: mvn deploy -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    - name: Prepare and Perform Maven Release
      run: mvn --batch-mode release:clean release:prepare release:perform -Darguments="-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true" -Dusername=${{ github.actor }} -Dpassword=${{ secrets.RELEASE_TOKEN }}
